### ISSUE TITLE
Manifest-Warning 'no version key'

### ISSUE THREAD

**Issue by tombrain** [HazardDede/home-assistant-ferienapidotde#1]
HA shows warning:
`No 'version' key in the manifest file for custom integration 'ferienapidotde'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'ferienapidotde'`
Plaese integrate the version

**Comment by HazardDede** [comment]
@tombrain `version` key was added. Thanks for reporting.
