### ISSUE TITLE
Info for next day

### ISSUE THREAD

**Issue by tombrain** [HazardDede/home-assistant-ferienapidotde#3]
Is it possible to get information for the following day?

**Comment by HazardDede** [comment]
Unfortunately not. The underlying `ferien-api` supports to pass a `datetime`-object to override `datetime.now`, but so far this component does not use it.

**Comment by f-zappa** [comment]
I have an automation which tells my children when it's time to turn off the light in the evening but until now it only includes workdays. Would be great to also respect school holidays, but this would also mean to get information for the next day. My suggestion would be to use the same "days_offset" parameter like in the workday integration.
Would it be much effort to integrate this?

**Comment by daemonenstall** [comment]
I have the same "problem" as @f-zappa 
Would be great to have the option "days_offset".
